services:
  postgres:
    image: postgres:15
    container_name: postgres_main
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infraestructura_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - infraestructura_network
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_main
    restart: no
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - infraestructura_network


  # Oracle XE (versión ligera para desarrollo)
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle_main
    restart: no
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"   # puerto base de datos
      - "5500:5500"   # Enterprise Manager
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - infraestructura_network

    
  mysql:
    image: mysql:8.0
    container_name: mysql_main
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infraestructura_network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: no
    ports:
      - "8978:8978"
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - infraestructura_network



volumes:
  postgres_data:
  sqlserver_data:
  mysql_data:
  oracle_data:
  dbeaver_data:

networks:
  infraestructura_network:
    external: true  